FROM python:3.10-slim-buster

WORKDIR /app

COPY requirements_streamlit.txt .
RUN pip install --no-cache-dir -r requirements_streamlit.txt

COPY . .

# Expose the port Streamlit listens on (default 8501)
EXPOSE 8501

CMD ["streamlit", "run", "app.py"]